name: nascentguruism

permalink: /journal/:title/
exclude:
- Gemfile
- Gemfile.lock
- README.md
- vendor

safe: true
lsi: false
pygments: true
markdown: kramdown
# Not sure if I want github flavoured markdown. Hmm.
# kramdown:
#   input: GFM
