name: Steve Marshall
url: http://stevemarshall.com

permalink: /journal/:title/
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- README.md

lsi: false

kramdown:
  input: GFM
  hard_wrap: false

gems:
- jekyll-default-layout
- jekyll-optional-front-matter
- jekyll-readme-index
- jekyll-titles-from-headings
