name: Steve Marshall
url: http://stevemarshall.com

permalink: /journal/:title/
exclude:
- CNAME
- Gemfile
- Gemfile.lock

lsi: false

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    block:
      line_numbers: true

plugins:
- jekyll-default-layout
- jekyll-optional-front-matter
- jekyll-readme-index
- jekyll-titles-from-headings
