name: Steve Marshall
url: http://stevemarshall.com

permalink: /journal/:title/
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- README.md

safe: true
lsi: false

kramdown:
  input: GFM
  hard_wrap: false
