name: Steve Marshall

permalink: /journal/:title/
exclude:
- Gemfile
- Gemfile.lock
- README.md
- vendor

safe: true
lsi: false
pygments: true

markdown: redcarpet
redcarpet:
  extensions:
    - autolink
    - no_intra_emphasis
    - safelink
    - smart
    - space_after_headers
    - strikethrough
    - superscript
    - tables
